made pre-commit run tests - and fixed code too

diff --git a/bin/pre-commit b/bin/pre-commit
--- a/bin/pre-commit
+++ b/bin/pre-commit
@@ -1,9 +1,15 @@
 #!/bin/sh
 # found http://blog.trondbjerkestrand.no/post/85120068477/sbt-and-git-pre-commit-hooks
-#if test $(sbt test | grep -c -E "Reformatted|Failed") != 0
 #if test $(sbt compile | grep -c -E "Reformatted|Failed") != 0
 if test $(sbt ";scalariformFormat;test:scalariformFormat" | grep -c -E "Reformatted|Failed") != 0
 then
 echo "Sbt detected problems. Code was not scalariformatted. It should be now."
 exit 1
 fi
+if test $(sbt test | grep -c -E "error.*Failed tests:") != 0
+then
+echo "sbt could not run tests."
+exit 1
+fi
+
+
